services:
  teidesat-cubesat-tracker:
    image: teidesat-cubesat-tracker:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teidesat-cubesat-tracker
    network_mode: host
    runtime: nvidia
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/root/.Xauthority:ro
      - .:/app
      - ${TRAINED_MODELS_PATH}:/app/trained-models
    device_cgroup_rules:
      - c 189:* rmw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /app
    command: "python3 main.py"
